# -------- This file is automatically generated by LSST's sconsUtils -------- #
__version__ = get_distribution('imgserv').version
__repo_version__ = 'unknown'
__fingerprint__ = 'b1a7b5fe30c6ec6a56dca1c1fc4ef559ab75e802 *'
__dependency_versions__ = {
    'boost': '1.66.0',
    'python': 'unknown',
    'boost_test': '1.66.0',
}
__all__ = ['__version__']
