# -------- This file is automatically generated by LSST's sconsUtils -------- #
__version__ = '1.0'
__repo_version__ = 'dax_latest'
__fingerprint__ = '8d09414389d9691835fab59d0dea64d2fa7e696c *'
__dependency_versions__ = {
    'boost': '1.69.lsst1',
    'python': 'unknown',
    'boost_test': '1.69.lsst1',
}
__all__ = (
    '__version__',
    '__repo_version__',
    '__fingerprint__',
    '__dependency_versions__',
)
